version: "3.9"

services:
    server:
        build: docker/node
        image: notes-backend
        container_name: notes-backend-server
        command: [ "npm", "start" ]
        tty: true
        user: "1000:1000"
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        env_file: &env_file
            - .env
        depends_on:
            - database

    database:
        container_name: notes-backend-database
        image: postgres:14-alpine
        healthcheck:
            test: [ "CMD", "/opt/healthcheck/postgres" ]
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./docker/healthcheck:/opt/healthcheck
        env_file: *env_file

volumes:
    postgres:
