info:
  version: 1.4.0
  title: Notes API
  description: Notes REST API definitions
paths:
  /api/v1/logout:
    post:
      responses:
        "204":
          description: When x-access-token is valid in headers
          content:
            "*/*":
              schema:
                type: object
                properties: {}
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;frame-ancestors 'self';img-src 'self'
                data:;object-src 'none';script-src 'self';script-src-attr
                'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            x-response-time:
              schema:
                type: string
              example: 8.979ms
            date:
              schema:
                type: string
              example: Thu, 21 Oct 2021 02:39:56 GMT
            connection:
              schema:
                type: string
              example: close
        "403":
          description: When x-access-token content is invalid in headers
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The provided access token content is not valid.
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;frame-ancestors 'self';img-src 'self'
                data:;object-src 'none';script-src 'self';script-src-attr
                'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "61"
            etag:
              schema:
                type: string
              example: W/"3d-RgWdMVHCl+4Q//C83jWHC27Udqw"
            x-response-time:
              schema:
                type: string
              example: 1.718ms
            date:
              schema:
                type: string
              example: Thu, 21 Oct 2021 02:39:56 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - user
  /api/v1/sign-up:
    post:
      responses:
        "201":
          description: When user is created successfully
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiYzEyZjBhZjEtZGMxZC00MzdkLTg4ZWMtNDUwZTZhYzY1N2Q5IiwiaWF0IjoxNjM0NzgzOTk3fQ.w_ifvT0odCsiXj0W3sW5jJFH5sh9ExlwchWPi0l76lE
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;frame-ancestors 'self';img-src 'self'
                data:;object-src 'none';script-src 'self';script-src-attr
                'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "186"
            etag:
              schema:
                type: string
              example: W/"ba-QHZuM20cicJ2f14Fr2rxYdGb7KA"
            x-response-time:
              schema:
                type: string
              example: 80.544ms
            date:
              schema:
                type: string
              example: Thu, 21 Oct 2021 02:39:57 GMT
            connection:
              schema:
                type: string
              example: close
        "400":
          description: When missing user data or password and password_confirmation are
            different
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '[body] - "name" is required'
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;frame-ancestors 'self';img-src 'self'
                data:;object-src 'none';script-src 'self';script-src-attr
                'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "43"
            etag:
              schema:
                type: string
              example: W/"2b-Ut9AyBpRYMoahJEbxWJIpyzPeb4"
            x-response-time:
              schema:
                type: string
              example: 1.121ms
            date:
              schema:
                type: string
              example: Thu, 21 Oct 2021 02:39:57 GMT
            connection:
              schema:
                type: string
              example: close
        "403":
          description: When email is already taken
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The provided email is already in use.
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;frame-ancestors 'self';img-src 'self'
                data:;object-src 'none';script-src 'self';script-src-attr
                'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "51"
            etag:
              schema:
                type: string
              example: W/"33-qYkUgf+EATQdI/509JnsWFdLTbs"
            x-response-time:
              schema:
                type: string
              example: 2.958ms
            date:
              schema:
                type: string
              example: Thu, 21 Oct 2021 02:39:57 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Brielle
                email:
                  type: string
                  example: Alysha_Christiansen@hotmail.com
                password:
                  type: string
                  example: VXlIGzHfb6Vz7pC
                password_confirmation:
                  type: string
                  example: VXlIGzHfb6Vz7pC
servers:
  - url: ""
    description: Notes Server
openapi: 3.0.3
