info:
  version: 1.4.0
  title: Notes API
  description: Notes REST API definitions
paths:
  /api/v1/sign-up:
    post:
      responses:
        "201":
          description: When user is created successfully
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZmQ3N2VkNzItNzJjYi00OWQxLTk5MGUtN2IyZTI5OGMxYmZkIiwiaWF0IjoxNjM0NjE0ODMzfQ.mKJOYt0h-fvTxKU7tMxnPRZhAObvEoq6qBWL2uRVEWI
          headers:
            x-powered-by:
              schema:
                type: string
              example: Express
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "186"
            etag:
              schema:
                type: string
              example: W/"ba-I7vfITMnsZs9LJqXW9P1WAzkVIY"
            x-response-time:
              schema:
                type: string
              example: 94.414ms
            date:
              schema:
                type: string
              example: Tue, 19 Oct 2021 03:40:33 GMT
            connection:
              schema:
                type: string
              example: close
        "400":
          description: When missing user data or password and password_confirmation are
            different
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '[body] - "name" is required'
          headers:
            x-powered-by:
              schema:
                type: string
              example: Express
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "43"
            etag:
              schema:
                type: string
              example: W/"2b-Ut9AyBpRYMoahJEbxWJIpyzPeb4"
            x-response-time:
              schema:
                type: string
              example: 2.808ms
            date:
              schema:
                type: string
              example: Tue, 19 Oct 2021 03:40:33 GMT
            connection:
              schema:
                type: string
              example: close
        "403":
          description: When email is already taken
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The provided email is already in use.
          headers:
            x-powered-by:
              schema:
                type: string
              example: Express
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "51"
            etag:
              schema:
                type: string
              example: W/"33-qYkUgf+EATQdI/509JnsWFdLTbs"
            x-response-time:
              schema:
                type: string
              example: 3.074ms
            date:
              schema:
                type: string
              example: Tue, 19 Oct 2021 03:40:33 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Alexzander
                email:
                  type: string
                  example: Lewis.Fay33@yahoo.com
                password:
                  type: string
                  example: KrDZh41X4k9jVv6
                password_confirmation:
                  type: string
                  example: KrDZh41X4k9jVv6
servers:
  - url: ""
    description: Notes Server
openapi: 3.0.3
