info:
  version: 1.4.0
  title: Notes API
  description: Notes REST API definitions
paths:
  /api/v1/sign-up:
    post:
      responses:
        "201":
          description: Created the user with success
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ0YTI5ZmMtYjExMy00MmRjLWE4NGItZmZiODBiODZmYTRjIiwiaWF0IjoxNjM0NTI3NjU1fQ.yBEiA6tqJVRRhlgbCBifcWbV-kbP0xC5Bwzn42PpKAg
          headers:
            x-powered-by:
              schema:
                type: string
              example: Express
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "186"
            etag:
              schema:
                type: string
              example: W/"ba-UzuZDn+o2SH5NdExzA4oVtBoCTI"
            x-response-time:
              schema:
                type: string
              example: 52.107ms
            date:
              schema:
                type: string
              example: Mon, 18 Oct 2021 03:27:35 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Dylan
                email:
                  type: string
                  example: Kiana.Streich59@hotmail.com
                password:
                  type: string
                  example: FssW31uotSB9g34
                password_confirmation:
                  type: string
                  example: FssW31uotSB9g34
servers:
  - url: ""
    description: Notes Server
openapi: 3.0.3
