info:
  version: 1.4.0
  title: Notes API
  description: Notes REST API definitions
paths:
  /api/v1/sign-up:
    post:
      responses:
        "201":
          description: Created the user with success
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMmJlZmY1ZWQtYTUyMS00NjEyLTg2ZGUtMjk5NzM4OTdlZDdkIiwiaWF0IjoxNjM0NTk0MDMzfQ.3awVQdonH0URnpBfaMdDD0RRWePt2ruo20d5oYKaXAc
          headers:
            x-powered-by:
              schema:
                type: string
              example: Express
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "186"
            etag:
              schema:
                type: string
              example: W/"ba-f2mzEHcqHwYUFsnfXqM+iQP5oLI"
            x-response-time:
              schema:
                type: string
              example: 72.865ms
            date:
              schema:
                type: string
              example: Mon, 18 Oct 2021 21:53:53 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Shanon
                email:
                  type: string
                  example: Lewis.Rippin@yahoo.com
                password:
                  type: string
                  example: VobJDfIdS5BN_jW
                password_confirmation:
                  type: string
                  example: VobJDfIdS5BN_jW
servers:
  - url: ""
    description: Notes Server
openapi: 3.0.3
